easy_admin:
    site_name: 'My Portfolio'
    entities:
        # List the entity class name you want to manage
        - App\Entity\User
        - App\Entity\Project
        - App\Entity\Diploma
        - App\Entity\Language
        - App\Entity\SpeakingLanguage
        - App\Entity\Skill
    design:
        menu:
            - { entity: 'User', icon: 'user' }
            - { entity: 'Project', icon: 'folder' }
            - { entity: 'Diploma', icon: 'certificate' }
            - { entity: 'Language', icon: 'tv' }
            - { entity: 'SpeakingLanguage', icon: 'language'}
            - { entity: 'Skill', icon: 'app-store' }
